sudo: false
language: cpp
python:
  - "3.7"
  - "pypy3"
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo apt-get install -y python-setuptools
  - sudo apt-get install python3-pip
  - pip install -r python/requirements.txt
before_install:
  - git submodule update --init --recursive
script:
  - make -f Makefile run_tests
  - ./run_tests.sh
  - cd python
  - python3 setup.py install
  - python3 pytest.py
notifications:
    slack: jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
    rooms:
      - jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
